In [38]:
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import time 

In [5]:
PATH=ChromeDriverManager().install()   # instala el driver

driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome

driver.get(URL + busqueda)     # entra en google

time.sleep(2)    # para 2 secs

driver.find_element(By.XPATH, '//*[@id="L2AGLb"]').click() # acepta cookies

2023-01-24 09:15:24,107 [45998] WARNING  py.warnings:109: [JupyterRequire] /var/folders/0p/q9p3n_m96v7fgw9v0l4dvkyr0000gn/T/ipykernel_45998/4006542889.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome



NameError: name 'URL' is not defined

In [41]:
driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome

driver.get('https://app.soundcharts.com') 

time.sleep(2)    # para 2 secs

driver.find_element(By.XPATH, '//*[@id="L2AGLb"]').click() 

2023-01-24 17:24:00,323 [45998] WARNING  py.warnings:109: [JupyterRequire] /var/folders/0p/q9p3n_m96v7fgw9v0l4dvkyr0000gn/T/ipykernel_45998/3480594190.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)         # abre una pestaña de chrome



NameError: name 'By' is not defined

In [40]:
opciones = Options()
opciones.add_experimental_option("excludeSwitches", ["enable-automation"])
opciones.add_experimental_option("useAutomationExtension", False)
opciones.headless = True  # si True, no aperece la ventana (headless=no visible)
opciones.add_argument("--start-maximized")  # comienza maximizado
opciones.add_argument("user-data-dir=selenium") 

In [9]:
a = np.random.random((2, 3, 5))

In [10]:
a

array([[[0.28585355, 0.00493518, 0.01291211, 0.40187527, 0.18582371],
        [0.66917973, 0.01654612, 0.66085186, 0.55326659, 0.06481066],
        [0.86272381, 0.59439958, 0.51833706, 0.11746803, 0.0948366 ]],

       [[0.16226027, 0.5982828 , 0.54145851, 0.53871387, 0.42986102],
        [0.66699404, 0.76238179, 0.03121657, 0.02434153, 0.2047694 ],
        [0.31029524, 0.26758995, 0.16334107, 0.21243011, 0.73540481]]])

In [12]:
b = np.ones((5, 2, 3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [13]:
np.size(a) == np.size(b)

True

In [15]:
c = b.transpose((1, 2, 0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [17]:
c.shape

(2, 3, 5)

In [18]:
d = np.add(a, c)

In [19]:
f = np.empty_like(d)

In [21]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [29]:
d = a+c

In [30]:
d_max =np.max(d)
d_min =np.min(d)
d_mean =np.mean(d)
print(d)

[[[1.28585355 1.00493518 1.01291211 1.40187527 1.18582371]
  [1.66917973 1.01654612 1.66085186 1.55326659 1.06481066]
  [1.86272381 1.59439958 1.51833706 1.11746803 1.0948366 ]]

 [[1.16226027 1.5982828  1.54145851 1.53871387 1.42986102]
  [1.66699404 1.76238179 1.03121657 1.02434153 1.2047694 ]
  [1.31029524 1.26758995 1.16334107 1.21243011 1.73540481]]]


In [31]:
f = np.empty(2,3,5)
print(d)

TypeError: Cannot interpret '3' as a data type

In [32]:
f = np.empty ((2,3,5))

In [33]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            e = d[i][j][k]
            if d_min < e < d_mean:
                f[i][j][k] = 25
            elif d_mean < e < d_max:
                f[i][j][k] = 75
            elif e == d_mean:
                f[i][j][k] = 50
            elif e == d_min:
                f[i][j][k] = 0
            elif e == d_max:
                f[i][j][k] = 100
print(d)
print(f)

[[[1.28585355 1.00493518 1.01291211 1.40187527 1.18582371]
  [1.66917973 1.01654612 1.66085186 1.55326659 1.06481066]
  [1.86272381 1.59439958 1.51833706 1.11746803 1.0948366 ]]

 [[1.16226027 1.5982828  1.54145851 1.53871387 1.42986102]
  [1.66699404 1.76238179 1.03121657 1.02434153 1.2047694 ]
  [1.31029524 1.26758995 1.16334107 1.21243011 1.73540481]]]
[[[ 25.   0.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [100.  75.  75.  25.  25.]]

 [[ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]]]
